name: Demo Workflow

on: [push] # specify events

jobs:
  run-shell-command:
    runs-on: ubuntu-latest # specify os
    steps:
      - name: echo a string
        run: echo "Hola mundo"
      - name: multiline script
        run: | # multiple commands
          node -v
          npm -v
      - name: Python commands
        run: |
          import platform
          print(platform.processor())
        shell: python # denotes custom shell
  run-macos-command:
    runs-on: "macos-latest"
    steps:
      - name: print version
        run: sw_vers
